; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[scampi]
platform = atmelmegaavr
board = ATtiny1616
board_build.f_cpu = 5000000L
monitor_speed = 115200
build_flags = 
	-Wall -Wextra
upload_protocol = atmelice_updi
lib_deps = 
	symlink://../common

[env:scampi]
extends = scampi
